# Tp << Inteligence artificielle pour la cybersecurité >>

## Partie 1 : Découverte a préparation de données

**Importation des bibliothéques**  
  

Les bibliothéques requises sont dans le fichier **requirements.txt**  
On peut les installer avec la commande : ***pip install -r requirements.txt***

In [152]:
# Dataframes annd array manipulation 

import numpy as np 
import pandas as pd 

# Plotting and figures 

import matplotlib.pyplot as plt 
import seaborn as  sns 

# Machine learning 

from sklearn.preprocessing import StandardScaler , MinMaxScaler , OneHotEncoder
from sklearn.model_selection import train_test_split , GridSearchCV 
from sklearn.metrics import confusion_matrix , accuracy_score 
from sklearn.neighbors import KNeighborsClassifier

In [101]:

df_test = pd.read_csv("NSL-KDD/KDDTest+.txt")
df_train = pd.read_csv("NSL-KDD/KDDTrain+.txt")


print(df_train.head())
print(df_test.head())

   duration protocol_type  ... sub_attack difficulty_level
0         0           tcp  ...     normal               20
1         0           udp  ...     normal               15
2         0           tcp  ...    neptune               19
3         0           tcp  ...     normal               21
4         0           tcp  ...     normal               21

[5 rows x 43 columns]
   duration protocol_type  ... sub_attack difficulty_level
0         0           tcp  ...    neptune               21
1         0           tcp  ...    neptune               21
2         2           tcp  ...     normal               21
3         0          icmp  ...      saint               15
4         1           tcp  ...      mscan               11

[5 rows x 43 columns]

In [102]:
print(df_test.info)
print(df_train.info)

<bound method DataFrame.info of        duration protocol_type  ... sub_attack difficulty_level
0             0           tcp  ...    neptune               21
1             0           tcp  ...    neptune               21
2             2           tcp  ...     normal               21
3             0          icmp  ...      saint               15
4             1           tcp  ...      mscan               11
...         ...           ...  ...        ...              ...
22539         0           tcp  ...     normal               21
22540         0           tcp  ...     normal               21
22541         0           tcp  ...       back               15
22542         0           udp  ...     normal               21
22543         0           tcp  ...      mscan               14

[22544 rows x 43 columns]>
<bound method DataFrame.info of         duration protocol_type  ... sub_attack difficulty_level
0              0           tcp  ...     normal               20
1              0           udp  ...     normal               15
2              0           tcp  ...    neptune               19
3              0           tcp  ...     normal               21
4              0           tcp  ...     normal               21
...          ...           ...  ...        ...              ...
125968         0           tcp  ...    neptune               20
125969         8           udp  ...     normal               21
125970         0           tcp  ...     normal               18
125971         0           tcp  ...    neptune               20
125972         0           tcp  ...     normal               21

[125973 rows x 43 columns]>

**Nombre d'observations :**  
- Dans le jeu de données d'entrainement : 125973 observation 
- Dans le jeu de données de test :  22544 observation

In [103]:
print("Nombre de variables : " , df_test.columns.shape[0]
)

Nombre de variables :  43

In [113]:
# Classe a predire 

print("Classe a predire : " , df_train.columns[-2])

Classe a predire :  sub_attack

In [105]:
# Variables numeriques / catégorielles 

#Variables numériques

print("Les variables numeriques : \n ")
for var in df_train.dtypes[(df_train.dtypes == "int64") | (df_train.dtypes == "float64")].index : 
    print(var)

Les variables numeriques :

duration
src_bytes
dst_bytes
land
wrong_fragment
urgent
hot
num_failed_logins
logged_in
num_compromised
root_shell
su_attempted
num_root
num_file_creations
num_shells
num_access_files
num_outbound_cmds
is_host_login
is_guest_login
count
srv_count
serror_rate
srv_serror_rate
rerror_rate
srv_rerror_rate
same_srv_rate
diff_srv_rate
srv_diff_host_rate
dst_host_count
dst_host_srv_count
dst_host_same_srv_rate
dst_host_diff_srv_rate
dst_host_same_src_port_rate
dst_host_srv_diff_host_rate
dst_host_serror_rate
dst_host_srv_serror_rate
dst_host_rerror_rate
dst_host_srv_rerror_rate
difficulty_level

In [106]:
print("Les variables categorielles : \n ")
for var in df_train.dtypes[(df_train.dtypes != "int64") & (df_train.dtypes != "float64")].index : 
    print(var)

Les variables categorielles :

protocol_type
service
flag
sub_attack

In [107]:
# Les differentes valeurs prises par les variables categorielles : 

print("Les differentes valeurs prises par variables categorielles : \n ")
for var in df_train.dtypes[(df_train.dtypes != "int64") & (df_train.dtypes != "float64")].index : 
    print("La variable " , var , ": \n")
    print(df_train[var].unique().var)
    print("\n\n")

Les differentes valeurs prises par variables categorielles :

La variable  protocol_type :

<bound method NumpyExtensionArray.var of <StringArray>
['tcp', 'udp', 'icmp']
Length: 3, dtype: str>



La variable  service :

<bound method NumpyExtensionArray.var of <StringArray>
[   'ftp_data',       'other',     'private',        'http',  'remote_job',
        'name',  'netbios_ns',       'eco_i',         'mtp',      'telnet',
      'finger',    'domain_u',      'supdup',   'uucp_path',      'Z39_50',
        'smtp',    'csnet_ns',        'uucp', 'netbios_dgm',       'urp_i',
        'auth',      'domain',         'ftp',         'bgp',        'ldap',
       'ecr_i',      'gopher',       'vmnet',      'systat',    'http_443',
         'efs',       'whois',       'imap4',    'iso_tsap',        'echo',
      'klogin',        'link',      'sunrpc',       'login',      'kshell',
     'sql_net',        'time',   'hostnames',        'exec',       'ntp_u',
     'discard',        'nntp',     'courier',         'ctf',         'ssh',
     'daytime',       'shell',     'netstat',       'pop_3',        'nnsp',
         'IRC',       'pop_2',     'printer',       'tim_i',     'pm_dump',
       'red_i', 'netbios_ssn',         'rje',         'X11',       'urh_i',
   'http_8001',         'aol',   'http_2784',      'tftp_u',     'harvest']
Length: 70, dtype: str>



La variable  flag :

<bound method NumpyExtensionArray.var of <StringArray>
['SF', 'S0', 'REJ', 'RSTR', 'SH', 'RSTO', 'S1', 'RSTOS0', 'S3', 'S2', 'OTH']
Length: 11, dtype: str>



La variable  sub_attack :

<bound method NumpyExtensionArray.var of <StringArray>
[         'normal',         'neptune',     'warezclient',         'ipsweep',
       'portsweep',        'teardrop',            'nmap',           'satan',
           'smurf',             'pod',            'back',    'guess_passwd',
       'ftp_write',        'multihop',         'rootkit', 'buffer_overflow',
            'imap',     'warezmaster',             'phf',            'land',
      'loadmodule',             'spy',            'perl']
Length: 23, dtype: str>

In [108]:

# Verification des valeurs nulls : 
Nulls_train = df_train.isnull().sum()
Nulls_test = df_test.isnull().sum()
print(Nulls_train[Nulls_train != 0])
print(Nulls_test[Nulls_test != 0])

Series([], dtype: int64)
Series([], dtype: int64)

Pas de valeurs nulls

In [109]:
# Statistiques discriptives 

# jeu de données de test 

df_test.describe()

           duration     src_bytes  ...  dst_host_srv_rerror_rate  difficulty_level
count  22544.000000  2.254400e+04  ...              22544.000000      22544.000000
mean     218.859076  1.039545e+04  ...                  0.226683         18.017965
std     1407.176612  4.727864e+05  ...                  0.400875          4.270361
min        0.000000  0.000000e+00  ...                  0.000000          0.000000
25%        0.000000  0.000000e+00  ...                  0.000000         17.000000
50%        0.000000  5.400000e+01  ...                  0.000000         20.000000
75%        0.000000  2.870000e+02  ...                  0.170000         21.000000
max    57715.000000  6.282565e+07  ...                  1.000000         21.000000

[8 rows x 39 columns]

In [110]:
# jeu de donnée d'entrainement 

df_train.describe()

           duration     src_bytes  ...  dst_host_srv_rerror_rate  difficulty_level
count  125973.00000  1.259730e+05  ...             125973.000000     125973.000000
mean      287.14465  4.556674e+04  ...                  0.120240         19.504060
std      2604.51531  5.870331e+06  ...                  0.319459          2.291503
min         0.00000  0.000000e+00  ...                  0.000000          0.000000
25%         0.00000  0.000000e+00  ...                  0.000000         18.000000
50%         0.00000  4.400000e+01  ...                  0.000000         20.000000
75%         0.00000  2.760000e+02  ...                  0.000000         21.000000
max     42908.00000  1.379964e+09  ...                  1.000000         21.000000

[8 rows x 39 columns]

In [119]:
# Distribution de labels originaux
print("distribution des labels originaux \n")
print("Dans le jeu d'entrainement \n ")
print(df_train["sub_attack"].value_counts())
print("\n")
print("Dans le jeu de test \n ")
print(df_test["sub_attack"].value_counts())
print("\n")

distribution des labels originaux

Dans le jeu d'entrainement

sub_attack
normal             67343
neptune            41214
satan               3633
ipsweep             3599
portsweep           2931
smurf               2646
nmap                1493
back                 956
teardrop             892
warezclient          890
pod                  201
guess_passwd          53
buffer_overflow       30
warezmaster           20
land                  18
imap                  11
rootkit               10
loadmodule             9
ftp_write              8
multihop               7
phf                    4
perl                   3
spy                    2
Name: count, dtype: int64


Dans le jeu de test

sub_attack
normal             9711
neptune            4657
guess_passwd       1231
mscan               996
warezmaster         944
apache2             737
satan               735
processtable        685
smurf               665
back                359
snmpguess           331
saint               319
mailbomb            293
snmpgetattack       178
portsweep           157
ipsweep             141
httptunnel          133
nmap                 73
pod                  41
buffer_overflow      20
multihop             18
named                17
ps                   15
sendmail             14
xterm                13
rootkit              13
teardrop             12
xlock                 9
land                  7
xsnoop                4
ftp_write             3
loadmodule            2
worm                  2
perl                  2
sqlattack             2
udpstorm              2
phf                   2
imap                  1
Name: count, dtype: int64

In [115]:
print("les differents types d'attaques presents : \n ")
for attack in df_train["sub_attack"].unique():
    print(attack)

les differents types d'attaques presents :

normal
neptune
warezclient
ipsweep
portsweep
teardrop
nmap
satan
smurf
pod
back
guess_passwd
ftp_write
multihop
rootkit
buffer_overflow
imap
warezmaster
phf
land
loadmodule
spy
perl

In [120]:
# categorization des attaques 
mapping_attaques = {
    'normal': 'Normal',
    
    # DoS (Denial of Service)
    'neptune': 'DoS', 'back': 'DoS', 'land': 'DoS', 'pod': 'DoS', 
    'smurf': 'DoS', 'teardrop': 'DoS', 'mailbomb': 'DoS', 'apache2': 'DoS', 
    'processtable': 'DoS', 'udpstorm': 'DoS', 'worm': 'DoS',
    
    # Probe (Scanning / Reconnaissance)
    'satan': 'Probe', 'ipsweep': 'Probe', 'nmap': 'Probe', 
    'portsweep': 'Probe', 'mscan': 'Probe', 'saint': 'Probe',
    
    # R2L (Remote to Local)
    'guess_passwd': 'R2L', 'ftp_write': 'R2L', 'imap': 'R2L', 'phf': 'R2L', 
    'multihop': 'R2L', 'warezmaster': 'R2L', 'warezclient': 'R2L', 'spy': 'R2L',
    'xlock': 'R2L', 'xsnoop': 'R2L', 'snmpguess': 'R2L', 'snmpgetattack': 'R2L',
    'httptunnel': 'R2L', 'sendmail': 'R2L', 'named': 'R2L',
    
    # U2R (User to Root)
    'buffer_overflow': 'U2R', 'loadmodule': 'U2R', 'rootkit': 'U2R', 
    'perl': 'U2R', 'sqlattack': 'U2R', 'xterm': 'U2R', 'ps': 'U2R'
}

In [122]:
def categoriser_attaque(label):
    return mapping_attaques.get(label, 'Inconnu')

df_train['attack_category'] = df_train["sub_attack"].apply(categoriser_attaque)
df_test['attack_category'] = df_test["sub_attack"].apply(categoriser_attaque)

In [126]:
# Distribution des cinq categories

# dans le jeu d'entrainement

print("distribution des cinq categoris dans le jeu d'entrainement \n")
print(df_train["attack_category"].value_counts())
print("\n")

# dans le jeu de test 
print("distribution des cinq categoris dans le jeu d'entrainement \n")
print(df_test["attack_category"].value_counts())
print("\n")

distribution des cinq categoris dans le jeu d'entrainement

attack_category
Normal    67343
DoS       45927
Probe     11656
R2L         995
U2R          52
Name: count, dtype: int64


distribution des cinq categoris dans le jeu d'entrainement

attack_category
Normal    9711
DoS       7460
R2L       2885
Probe     2421
U2R         67
Name: count, dtype: int64

In [ ]:

# construction de la cible y 

def construction_cible(df):
     df["y"] = df["attack_category"].map({'Normal' :0 , 'DoS' : 1 , 'Probe' : 2 , 'R2L' : 3 , 'U2R' : 4})
     return df

df_train = construction_cible(df_train)
df_test = construction_cible(df_test)

print(df_test["y"].value_counts() , df_train["y"].value_counts())

y
0    9711
1    7460
3    2885
2    2421
4      67
Name: count, dtype: int64 y
0    67343
1    45927
2    11656
3      995
4       52
Name: count, dtype: int64

In [132]:
print(df_train.columns)
print(df_test.columns)

Index(['duration', 'protocol_type', 'service', 'flag', 'src_bytes',
       'dst_bytes', 'land', 'wrong_fragment', 'urgent', 'hot',
       'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell',
       'su_attempted', 'num_root', 'num_file_creations', 'num_shells',
       'num_access_files', 'num_outbound_cmds', 'is_host_login',
       'is_guest_login', 'count', 'srv_count', 'serror_rate',
       'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate',
       'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count',
       'dst_host_srv_count', 'dst_host_same_srv_rate',
       'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
       'dst_host_srv_diff_host_rate', 'dst_host_serror_rate',
       'dst_host_srv_serror_rate', 'dst_host_rerror_rate',
       'dst_host_srv_rerror_rate', 'sub_attack', 'difficulty_level',
       'attack_category', 'y'],
      dtype='str')
Index(['duration', 'protocol_type', 'service', 'flag', 'src_bytes',
       'dst_bytes', 'land', 'wrong_fragment', 'urgent', 'hot',
       'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell',
       'su_attempted', 'num_root', 'num_file_creations', 'num_shells',
       'num_access_files', 'num_outbound_cmds', 'is_host_login',
       'is_guest_login', 'count', 'srv_count', 'serror_rate',
       'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate',
       'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count',
       'dst_host_srv_count', 'dst_host_same_srv_rate',
       'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
       'dst_host_srv_diff_host_rate', 'dst_host_serror_rate',
       'dst_host_srv_serror_rate', 'dst_host_rerror_rate',
       'dst_host_srv_rerror_rate', 'sub_attack', 'difficulty_level',
       'attack_category', 'y'],
      dtype='str')

In [135]:
# Suppression des valeurs cibles precedentes 

df_train = df_train.drop(columns = ['sub_attack' , 'attack_category'])
df_test = df_test.drop(columns=['sub_attack' , 'attack_category'])

In [136]:
# Separation cible / vars explicatives 

x_train = df_train.drop(columns = ["y"]) # tests 
y_train = df_train["y"] # answers

x_test =  df_test.drop(columns = ["y"]) 
y_test =  df_test["y"] 

print(x_train.head())
print(x_test.head())
print(y_train.head())
print(y_test.head())

   duration protocol_type  ... dst_host_srv_rerror_rate difficulty_level
0         0           tcp  ...                     0.00               20
1         0           udp  ...                     0.00               15
2         0           tcp  ...                     0.00               19
3         0           tcp  ...                     0.01               21
4         0           tcp  ...                     0.00               21

[5 rows x 42 columns]
   duration protocol_type  ... dst_host_srv_rerror_rate difficulty_level
0         0           tcp  ...                     1.00               21
1         0           tcp  ...                     1.00               21
2         2           tcp  ...                     0.00               21
3         0          icmp  ...                     0.00               15
4         1           tcp  ...                     0.71               11

[5 rows x 42 columns]
0    0
1    0
2    1
3    0
4    0
Name: y, dtype: int64
0    1
1    1
2    0
3    2
4    2
Name: y, dtype: int64

In [ ]:
# Separation des variables categoriques et variables numeriques 

cat = ["protocol_type" , "service" , "flag"] # variables categoriques 

# variables numeriques 

x_train_num = x_train.drop(columns = cat) 
x_test_num = x_test.drop(columns = cat) 


print(x_train_num.dtypes)

print(x_test_num.dtypes)

duration                         int64
src_bytes                        int64
dst_bytes                        int64
land                             int64
wrong_fragment                   int64
urgent                           int64
hot                              int64
num_failed_logins                int64
logged_in                        int64
num_compromised                  int64
root_shell                       int64
su_attempted                     int64
num_root                         int64
num_file_creations               int64
num_shells                       int64
num_access_files                 int64
num_outbound_cmds                int64
is_host_login                    int64
is_guest_login                   int64
count                            int64
srv_count                        int64
serror_rate                    float64
srv_serror_rate                float64
rerror_rate                    float64
srv_rerror_rate                float64
same_srv_rate                  float64
diff_srv_rate                  float64
srv_diff_host_rate             float64
dst_host_count                   int64
dst_host_srv_count               int64
dst_host_same_srv_rate         float64
dst_host_diff_srv_rate         float64
dst_host_same_src_port_rate    float64
dst_host_srv_diff_host_rate    float64
dst_host_serror_rate           float64
dst_host_srv_serror_rate       float64
dst_host_rerror_rate           float64
dst_host_srv_rerror_rate       float64
difficulty_level                 int64
dtype: object
duration                         int64
src_bytes                        int64
dst_bytes                        int64
land                             int64
wrong_fragment                   int64
urgent                           int64
hot                              int64
num_failed_logins                int64
logged_in                        int64
num_compromised                  int64
root_shell                       int64
su_attempted                     int64
num_root                         int64
num_file_creations               int64
num_shells                       int64
num_access_files                 int64
num_outbound_cmds                int64
is_host_login                    int64
is_guest_login                   int64
count                            int64
srv_count                        int64
serror_rate                    float64
srv_serror_rate                float64
rerror_rate                    float64
srv_rerror_rate                float64
same_srv_rate                  float64
diff_srv_rate                  float64
srv_diff_host_rate             float64
dst_host_count                   int64
dst_host_srv_count               int64
dst_host_same_srv_rate         float64
dst_host_diff_srv_rate         float64
dst_host_same_src_port_rate    float64
dst_host_srv_diff_host_rate    float64
dst_host_serror_rate           float64
dst_host_srv_serror_rate       float64
dst_host_rerror_rate           float64
dst_host_srv_rerror_rate       float64
difficulty_level                 int64
dtype: object

In [151]:
# variables categoriques 
x_train_cat = x_train[cat]
x_test_cat = x_test[cat]

print(x_train_cat.dtypes)
print(x_test_cat.dtypes)

protocol_type    str
service          str
flag             str
dtype: object
protocol_type    str
service          str
flag             str
dtype: object

In [159]:
# Encodage des variables categoriques : One Hot Encoding 

# instance de Onhotencoder
ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore')



encoded_train = ohe.fit_transform(x_train_cat)

# 2. Transform ONLY the test data (do NOT call fit_transform here)
encoded_test = ohe.transform(x_test_cat)

# 3. Extract column names from the fitted encoder
feature_names = ohe.get_feature_names_out(cat)

# 4. Create DataFrames
x_train_cat_encoded = pd.DataFrame(encoded_train, columns=feature_names, dtype=int)
x_test_cat_encoded = pd.DataFrame(encoded_test, columns=feature_names, dtype=int)

print(x_train_cat_encoded.head())
print(x_test_cat_encoded.head())
print(x_train_cat_encoded.columns)
print(x_test_cat_encoded.columns)

   protocol_type_icmp  protocol_type_tcp  ...  flag_SF  flag_SH
0                   0                  1  ...        1        0
1                   0                  0  ...        1        0
2                   0                  1  ...        0        0
3                   0                  1  ...        1        0
4                   0                  1  ...        1        0

[5 rows x 84 columns]
   protocol_type_icmp  protocol_type_tcp  ...  flag_SF  flag_SH
0                   0                  1  ...        0        0
1                   0                  1  ...        0        0
2                   0                  1  ...        1        0
3                   1                  0  ...        1        0
4                   0                  1  ...        0        0

[5 rows x 84 columns]
Index(['protocol_type_icmp', 'protocol_type_tcp', 'protocol_type_udp',
       'service_IRC', 'service_X11', 'service_Z39_50', 'service_aol',
       'service_auth', 'service_bgp', 'service_courier', 'service_csnet_ns',
       'service_ctf', 'service_daytime', 'service_discard', 'service_domain',
       'service_domain_u', 'service_echo', 'service_eco_i', 'service_ecr_i',
       'service_efs', 'service_exec', 'service_finger', 'service_ftp',
       'service_ftp_data', 'service_gopher', 'service_harvest',
       'service_hostnames', 'service_http', 'service_http_2784',
       'service_http_443', 'service_http_8001', 'service_imap4',
       'service_iso_tsap', 'service_klogin', 'service_kshell', 'service_ldap',
       'service_link', 'service_login', 'service_mtp', 'service_name',
       'service_netbios_dgm', 'service_netbios_ns', 'service_netbios_ssn',
       'service_netstat', 'service_nnsp', 'service_nntp', 'service_ntp_u',
       'service_other', 'service_pm_dump', 'service_pop_2', 'service_pop_3',
       'service_printer', 'service_private', 'service_red_i',
       'service_remote_job', 'service_rje', 'service_shell', 'service_smtp',
       'service_sql_net', 'service_ssh', 'service_sunrpc', 'service_supdup',
       'service_systat', 'service_telnet', 'service_tftp_u', 'service_tim_i',
       'service_time', 'service_urh_i', 'service_urp_i', 'service_uucp',
       'service_uucp_path', 'service_vmnet', 'service_whois', 'flag_OTH',
       'flag_REJ', 'flag_RSTO', 'flag_RSTOS0', 'flag_RSTR', 'flag_S0',
       'flag_S1', 'flag_S2', 'flag_S3', 'flag_SF', 'flag_SH'],
      dtype='str')
Index(['protocol_type_icmp', 'protocol_type_tcp', 'protocol_type_udp',
       'service_IRC', 'service_X11', 'service_Z39_50', 'service_aol',
       'service_auth', 'service_bgp', 'service_courier', 'service_csnet_ns',
       'service_ctf', 'service_daytime', 'service_discard', 'service_domain',
       'service_domain_u', 'service_echo', 'service_eco_i', 'service_ecr_i',
       'service_efs', 'service_exec', 'service_finger', 'service_ftp',
       'service_ftp_data', 'service_gopher', 'service_harvest',
       'service_hostnames', 'service_http', 'service_http_2784',
       'service_http_443', 'service_http_8001', 'service_imap4',
       'service_iso_tsap', 'service_klogin', 'service_kshell', 'service_ldap',
       'service_link', 'service_login', 'service_mtp', 'service_name',
       'service_netbios_dgm', 'service_netbios_ns', 'service_netbios_ssn',
       'service_netstat', 'service_nnsp', 'service_nntp', 'service_ntp_u',
       'service_other', 'service_pm_dump', 'service_pop_2', 'service_pop_3',
       'service_printer', 'service_private', 'service_red_i',
       'service_remote_job', 'service_rje', 'service_shell', 'service_smtp',
       'service_sql_net', 'service_ssh', 'service_sunrpc', 'service_supdup',
       'service_systat', 'service_telnet', 'service_tftp_u', 'service_tim_i',
       'service_time', 'service_urh_i', 'service_urp_i', 'service_uucp',
       'service_uucp_path', 'service_vmnet', 'service_whois', 'flag_OTH',
       'flag_REJ', 'flag_RSTO', 'flag_RSTOS0', 'flag_RSTR', 'flag_S0',
       'flag_S1', 'flag_S2', 'flag_S3', 'flag_SF', 'flag_SH'],
      dtype='str')

In [168]:
# La nouvelle dimension de x

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(125973, 123)
(22544, 123)
(125973,)
(22544,)

In [ ]:
# jeu de données completemnt numerique

x_train = pd.concat([x_train_num , x_train_cat_encoded], axis =1)
x_test = pd.concat([x_test_num, x_test_cat_encoded], axis =1)

print(x_train.dtypes[(x_train.dtypes != "int64")&(x_train.dtypes !="float64")])
print(x_test.dtypes[(x_test.dtypes != "int64")&(x_test.dtypes !="float64")])

print("Tous les donneés sont numériques")

Series([], dtype: object)
Series([], dtype: object)
Tous les donneés sont numériques

In [169]:
# SEPARATION APPRENTISSAGE / TEST 

x_train , x_val , y_train , y_val = train_test_split(x_train,y_train, test_size = 0.2, random_state = 42 )

print(x_train.shape)
print(x_val.shape)

print(y_train.shape)
print(y_val.shape)

(100778, 123)
(25195, 123)
(100778,)
(25195,)

In [170]:
# Scaling data 

# On utitlise le StandardScaler

scaler = StandardScaler()
x_train  = scaler.fit_transform(x_train)
x_val = scaler.transform(x_val)
x_test = scaler.transform(x_test)

In [ ]:
# Verification finale

In [ ]:
# Dimensions 
print("La dimension de x_train : ",x_train.shape )
print("La dimension de x_val : ", x_val.shape )
print("La dimension de x_test : ",x_test.shape )
print("La dimension de y_train : ", y_train.shape )
print("La dimension de y_val : ", y_val.shape )
print("La dimension de y_test : ",y_test.shape )

print("\n\n")

print("le type de x_train " , x_train.dtype)
print("le type de x_val " , x_val.dtype)
print("le type de x_test " , x_test.dtype)

print("le type de y_train " , x_train.dtype)
print("le type de y_val " , x_val.dtype)
print("le type de y_test " , x_test.dtype)

print("\n\n")

print("les classes dans y_train : " , y_train.unique())
print("les classes dans y_val : " , y_val.unique())
print("les classes dans y_test : " , y_test.unique())

# Standardisation 

print("\n\n Verification de la standardisation , (moyenne proche de 0 , ecart type proche de 1)\n\n")

print("moyenne x_train" , np.mean(x_train))
print("moyenne x_val" , np.mean(x_val))
print("moyenne x_test" , np.mean(x_test))

print("\n")

print("ecart type x_train" , np.std(x_train))
print("ecart type x_val" , np.std(x_val))
print("ecart type x_test" , np.std(x_test))

print("\n Les valeurs sont standardisés")

La dimension de x_train :  (100778, 123)
La dimension de x_val :  (25195, 123)
La dimension de x_test :  (22544, 123)
La dimension de y_train :  (100778,)
La dimension de y_val :  (25195,)
La dimension de y_test :  (22544,)



le type de x_train  float64
le type de x_val  float64
le type de x_test  float64
le type de y_train  float64
le type de y_val  float64
le type de y_test  float64



les classes dans y_train :  [0 1 2 3 4]
les classes dans y_val :  [0 1 2 3 4]
les classes dans y_test :  [1 0 2 3 4]


 Verification de la standardisation , (moyenne proche de 0 , ecart type proche de 1)


moyenne x_train -3.842849380224868e-18
moyenne x_val -0.00011070736169709524
moyenne x_test 0.011553451693542369


ecart type x_train 0.9959266633137136
ecart type x_val 1.0070135981251496
ecart type x_test 1.388798880152258

 Les valeurs sont standardisés